<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required userData</value>
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required appendOverwriteFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nIHN0
clVzZXJEYXRhID0gbnVsbDsKU3RyaW5nIHN0ckZ1bGxGaWxlbmFtZSA9IG51bGw7CmlmIChpZGNQ
aXBlbGluZS5maXJzdCgidXNlckRhdGEiKSkKewogIHN0clVzZXJEYXRhID0gKFN0cmluZykgaWRj
UGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImZpbGVuYW1lIikp
CnsKICBzdHJGdWxsRmlsZW5hbWUgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwp9
CmVsc2UKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJmaWxlbmFtZSBpcyBudWxsISIp
Owp9CmlkY1BpcGVsaW5lLmZpcnN0KCJhcHBlbmRPdmVyd3JpdGVGbGFnIik7ClN0cmluZyBhcHBl
bmRPdmVyd3JpdGVGbGFnID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKCi8vIFNl
cGFyYXRlIGZpbGVuYW1lIGludG8gcGF0aCBhbmQgZmlsZW5hbWUKLy8gVGhpcyBpcyBkb25lIHNv
IHRoYXQgdGhlIGRpcmVjdG9yeSBjYW4gYmUgd3JpdHRlbiAoaWYgbmVjZXNzYXJ5KQpTdHJpbmcg
c2VwYXJhdG9yID0gU3lzdGVtLmdldFByb3BlcnR5KCJmaWxlLnNlcGFyYXRvciIpOwppbnQgaW5k
ZXhTZXBhcmF0b3IgPSBzdHJGdWxsRmlsZW5hbWUubGFzdEluZGV4T2Yoc2VwYXJhdG9yKTsKaWYg
KGluZGV4U2VwYXJhdG9yID09IC0xKQp7CiAgLy8gQWNjb3VudCBmb3IgZmFjdCB0aGF0IHlvdSBj
YW4gdXNlIGVpdGhlciAnXCcgb3IgJy8nIGluIFdpbmRvd3MKICBpbmRleFNlcGFyYXRvciA9IHN0
ckZ1bGxGaWxlbmFtZS5sYXN0SW5kZXhPZignLycpOwp9ClN0cmluZyBzdHJQYXRoTmFtZSA9IHN0
ckZ1bGxGaWxlbmFtZS5zdWJzdHJpbmcoMCwgaW5kZXhTZXBhcmF0b3IgKyAxKTsKU3RyaW5nIHN0
ckZpbGVOYW1lID0gc3RyRnVsbEZpbGVuYW1lLnN1YnN0cmluZyhpbmRleFNlcGFyYXRvciArIDEp
OwoKRmlsZVdyaXRlciBmdyA9IG51bGw7CnRyeQp7CiAgRmlsZSBwYXRoVG9CZVdyaXR0ZW4gPSBu
ZXcgRmlsZShzdHJQYXRoTmFtZSk7CiAgLy8gU3lzdGVtLm91dC5wcmludGxuKCJjYW5vbmljYWwg
cGF0aCA9ICIgKwogIC8vIHBhdGhUb0JlV3JpdHRlbi5nZXRDYW5vbmljYWxQYXRoKCkpOwoKICAv
LyBXcml0ZSB0aGUgZGlyZWN0b3J5Li4uCiAgaWYgKHBhdGhUb0JlV3JpdHRlbi5leGlzdHMoKSA9
PSBmYWxzZSkKICB7CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiUGF0aCBkb2VzIG5v
dCBleGlzdCEiKTsKICB9CgogIC8vIENoZWNrIGlmIGZpbGUgZXhpc3RzCiAgRmlsZSBmaWxlVG9C
ZVdyaXR0ZW4gPSBuZXcgRmlsZShzdHJGdWxsRmlsZW5hbWUpOwogIGlmIChmaWxlVG9CZVdyaXR0
ZW4uZXhpc3RzKCkgPT0gdHJ1ZSAmJiBhcHBlbmRPdmVyd3JpdGVGbGFnICE9IG51bGwgJiYgYXBw
ZW5kT3ZlcndyaXRlRmxhZy5lcXVhbHMoImZhaWxJZkZpbGVFeGlzdHMiKSkKICB7CiAgICB0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRmlsZSAiICsgc3RyRnVsbEZpbGVuYW1lICsgIiBhbHJl
YWR5IGV4aXN0cyEiKTsKICB9CgogIC8vIFdyaXRlIHRoZSBmaWxlLi4uCiAgaWYgKGFwcGVuZE92
ZXJ3cml0ZUZsYWcgIT0gbnVsbCAmJiBhcHBlbmRPdmVyd3JpdGVGbGFnLmVxdWFscygib3Zlcndy
aXRlIikpCiAgewogICAgLy8gb3ZlcndyaXRlCiAgICBmdyA9IG5ldyBGaWxlV3JpdGVyKHN0ckZ1
bGxGaWxlbmFtZSwgZmFsc2UpOwogIH0KICBlbHNlCiAgewogICAgLy8gYXBwZW5kCiAgICBmdyA9
IG5ldyBGaWxlV3JpdGVyKHN0ckZ1bGxGaWxlbmFtZSwgdHJ1ZSk7CiAgfQogIGZ3LndyaXRlKHN0
clVzZXJEYXRhKTsKfQpjYXRjaCAoRXhjZXB0aW9uIGUpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7Cn0KZmluYWxseQp7CiAgLy8gQ2xvc2UgdGhlIG91dHB1
dCBzdHJlYW0uLi4uCiAgdHJ5CiAgewogICAgZncuY2xvc2UoKTsKICB9CiAgY2F0Y2ggKEV4Y2Vw
dGlvbiBlKQogIHsKICB9CgogIGlkY1BpcGVsaW5lLmRlc3Ryb3koKTsKfQoJCg==</value>
</Values>
