<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">moveFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required sourcePath</value>
    <value>[i] field:0:required targetDir</value>
    <value>[i] field:0:required useTimeStamp {"false","true"}</value>
    <value>[o] field:0:required status</value>
    <value>[o] field:0:required targetFilePath</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmcgc291cmNl
UGF0aCA9IG51bGw7ClN0cmluZyB0YXJnZXREaXIgPSBudWxsOwoKaWYgKGN1cnNvci5maXJzdCgi
c291cmNlUGF0aCIpKQp7CiAgc291cmNlUGF0aCA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgp
Owp9CmVsc2UKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnB1dCBwYXJhbWV0ZXIg
XCdzb3VyY2VQYXRoXCcgd2FzIG5vdCBmb3VuZC4iKTsKfQppZiAoY3Vyc29yLmZpcnN0KCJ0YXJn
ZXREaXIiKSkKewogIHRhcmdldERpciA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOwp9CmVs
c2UKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnB1dCBwYXJhbWV0ZXIgXCd0YXJn
ZXREaXJcJyB3YXMgbm90IGZvdW5kLiIpOwp9CmJvb2xlYW4gdXNlVGltZVN0YW1wID0gY3Vyc29y
LmZpcnN0KCJ1c2VUaW1lU3RhbXAiKSA/IEJvb2xlYW4udmFsdWVPZigoU3RyaW5nKSBjdXJzb3Iu
Z2V0VmFsdWUoKSkuYm9vbGVhblZhbHVlKCkgOiBmYWxzZTsKY3Vyc29yLmRlc3Ryb3koKTsKCmJv
b2xlYW4gc3RhdHVzID0gZmFsc2U7CkZpbGUgb3JpZ2luYWwgPSBuZXcgRmlsZShzb3VyY2VQYXRo
KTsKCi8vIFN0cmluZyBkdFN0YW1wID0gbmV3IERhdGUoKS50b1N0cmluZygpLnJlcGxhY2UoJyAn
LCAnLScpLnJlcGxhY2UoJzonLAovLyAnLScpOwpTdHJpbmcgZHRTdGFtcCA9IG51bGw7CnRyeQp7
CiAgSURhdGEgZCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKICBJRGF0YUN1cnNvciBjID0gZC5n
ZXRDdXJzb3IoKTsKICBjLmZpcnN0KCk7CiAgYy5pbnNlcnRCZWZvcmUoInBhdHRlcm4iLCAieXl5
eU1NZGRISG1tc3MiKTsKICBJRGF0YSBkMiA9IFNlcnZpY2UuZG9JbnZva2UoInB1Yi5kYXRlIiwg
ImN1cnJlbnREYXRlIiwgZCk7CiAgYyA9IGQyLmdldEN1cnNvcigpOwogIGlmIChjLmZpcnN0KCJ2
YWx1ZSIpKQogIHsKICAgIGR0U3RhbXAgPSAoU3RyaW5nKSBjLmdldFZhbHVlKCk7CiAgfQogIGVs
c2UKICB7CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTWlzc2luZyByZXR1cm5lZCB2
YWx1ZSBmb3IgU2VydmljZSBjdXJyZW50RGF0ZS4iKTsKICB9Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBl
KQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9ClN0cmlu
ZyBiYXNlbmFtZSA9IG9yaWdpbmFsLmdldE5hbWUoKTsKaWYgKHVzZVRpbWVTdGFtcCkKewogIGJh
c2VuYW1lICs9ICItIiArIGR0U3RhbXA7Cn0KRmlsZSB0YXJnZXRGaWxlID0gbmV3IEZpbGUodGFy
Z2V0RGlyLCBiYXNlbmFtZSk7CnN0YXR1cyA9IG9yaWdpbmFsLnJlbmFtZVRvKHRhcmdldEZpbGUp
OwpTdHJpbmcgdGFyZ2V0RmlsZVBhdGggPSBudWxsOwp0cnkKewogIHRhcmdldEZpbGVQYXRoID0g
dGFyZ2V0RmlsZS5nZXRDYW5vbmljYWxQYXRoKCk7Cn0KY2F0Y2ggKElPRXhjZXB0aW9uIGUpCnsK
ICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTW92ZSBmaWxlIGFuZCBvYnRhaW4gdGFyZ2V0
IHBhdGg6ICIgKyBlLmdldE1lc3NhZ2UoKSk7Cn0KY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29y
KCk7CmN1cnNvci5sYXN0KCk7CmN1cnNvci5pbnNlcnRBZnRlcigic3RhdHVzIiwgIiIgKyBzdGF0
dXMpOwpjdXJzb3IuaW5zZXJ0QWZ0ZXIoInRhcmdldEZpbGVQYXRoIiwgdGFyZ2V0RmlsZVBhdGgp
OwpjdXJzb3IuZGVzdHJveSgpOwoJCg==</value>
</Values>
